### ISSUE TITLE
Maven artefact not available

### ISSUE THREAD

**Issue by ScottDennison** [uwol/proleap-vb6-parser#18]
I notice that in the commit to the readme on July 24th 2018 and 23rd September 2018, the instructions to use the repository http://maven.proleap.io have been removed, and the current instructions seem to point to using a standard maven central hosted artefact.

However, I am unable to locate the artefact on maven central, and maven.proleap.io has been taken down.

Is there an official location for the artefact?

**Comment by uwol** [comment]
Currently there is no version deployed on a repository. However you can simply download and run `mvn clean install` locally to build and install the library for your maven projects.
